//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int id { get; set; }
        public Nullable<int> matchMakerId { get; set; }
        public Nullable<int> firstParticipantId { get; set; }
        public Nullable<int> secondParticipantId { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual MatchMaker MatchMaker { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Participant Participant1 { get; set; }
        public virtual Participant Participant2 { get; set; }
    }
}
